### ISSUE TITLE
Description in docs

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/wub#1]
Hi,

Minor issue in readthedocs:
I think the description of convert_alphabet was erroneous copied from sequence_filter, as those are identical and doesn't seem to fit the purpose of convert_alphabet
http://wub.readthedocs.io/en/latest/cmd_list.html#convert-alphabet

Cheers,
Wouter

**Comment by bsipos** [comment]
Thanks for reporting this issue. There were some problems with documentation generation so the HTML version was lagging behind.
