### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Adelaam** [nanoporetech/wub#3]
Hello,

I am trying to install wub on linux mint with:
git clone https://github.com/nanoporetech/wub.git
cd wub
python setup.py install
When I run the test I get: 34 passed, 1 skipped in 3.92 seconds 
But when I run make docs I get this error:
/home/mwiks/wub/docs/cmd_list.rst:7: WARNING: malformed hyperlink target.
None:5: WARNING: Unexpected indentation.
/home/mwiks/wub/docs/cmd_list.rst:7: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/mwiks/wub/wub/simulate/seq.py:docstring of wub.simulate.seq.simulate_sequencing_errors:6: WARNING: Field list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] wub.wrappers                                           
generating indices... genindex py-modindex
highlighting module code... [100%] wub.wrappers.dnadiff                         
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 4 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
make[1]: Leaving directory '/home/mwiks/wub/docs'
Do you what is the problem?

Thank you!

**Comment by bsipos** [comment]
Hello,

Have you tried running any of the tools? It seems to me that the installation was successful. You have one test skipped as probably you don't have a required dependency.

Best,
Botond

**Comment by Adelaam** [comment]
Yes, I have tried and I get this error: 
'/home/mwiks/wub/scripts/bam_accuracy.py' '/home/mwiks/mergedbacode03.bam' 
Traceback (most recent call last):
  File "/home/mwiks/wub/scripts/bam_accuracy.py", line 116, in <module>
    args.bam, region=args.c, min_aqual=args.q, with_clipps=args.e, verbose=not args.Q)
  File "/home/mwiks/wub/wub/bam/stats.py", line 147, in read_stats
    bam_reader = bam_common.pysam_open(bam, in_format='BAM')
  File "/home/mwiks/wub/wub/bam/common.py", line 21, in pysam_open
    aln_iter = pysam.AlignmentFile(alignment_file, mode)
  File "pysam/libcalignmentfile.pyx", line 729, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 969, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
a pdf folder has been made but I cannot open it.
Thank you!

**Comment by bsipos** [comment]
Looks like you might have a problem with the input file. Try running "samtools view /home/mwiks/mergedbacode03.bam" and see if it works.

Botond

**Comment by Adelaam** [comment]
I have tried with a different one and it is working!

Thank you for your help.
Adela
