### ISSUE TITLE
Plots 

### ISSUE THREAD

**Issue by Adelaam** [nanoporetech/wub#5]
Hello,

Do you know where can I find an explanation about the plots got from wub?
I think this tool is very useful and I would like to know exactly what information I am getting from it.

Thank you.

**Comment by Adelaam** [comment]
I am interesting in bam alignment qc, bam alignments compare bam accuracy and bam  multi qc

**Comment by bsipos** [comment]
Could you please address your question to support@nanoporetech.com? It would also help if in the email you could narrow down the set of plots you are interested in.

**Comment by Adelaam** [comment]
Ok, I will.
Thank you
