### ISSUE TITLE
bam_alignment_qc - error

### ISSUE THREAD

**Issue by Wildstrubu** [nanoporetech/wub#7]
Hi,

I always get the error at the end of the bam_alignment_qc run. The bam file is sorted and I removed all secondary alignments using "samtools view -F 256 input.bam > output.bam", because I wasn't sure whether that may cause the error as I used minimap2.

Has anyone see this before:
Gathering read and error statistics from file: /Data/mini_align/sorted.primary.bam
407037it [39:02, 173.73it/s] 
  File "/user/wub/scripts/bam_alignment_qc.py", line 289, in <module>
    error_stat_qc(error_stats, plotter, context_sizes, ommit_diagonal=True)
  File "/user/wub/scripts/bam_alignment_qc.py", line 256, in error_stat_qc
    if b in nd[cont]:
KeyError: 'AAA'

Many thanks for any inputs

**Comment by pphector** [comment]
I'm also seeing this error frequently and it is very annoying. Unfortunately, it seems like this package is not in active development so I don't think we will receive a reply. 

Has anyone figured out what triggers this issue?

**Comment by bsipos** [comment]
Indeed the package is no longer under active development hence will not investigate the issue more in-depth. However, specifying `-n "(1,0)"` is worth a try.
